# Generated by Django 6.0 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
