# Generated by Django 6.0.6 on 2026-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0003_cpu_affiliate_url_cpu_price_gpu_affiliate_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuiltPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('cpu_details', models.CharField(max_length=200)),
                ('gpu_details', models.CharField(max_length=200)),
                ('ram_details', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliate_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
