# Generated by Django 6.0.6 on 2026-06-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0004_prebuiltpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('motherboard_support', models.CharField(help_text='e.g. ATX, Micro-ATX, Mini-ITX', max_length=100)),
                ('max_gpu_length_mm', models.PositiveIntegerField(help_text='Max supported GPU length in mm')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliate_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_length_mm',
            field=models.PositiveIntegerField(default=280, help_text='GPU Length in mm'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='compatibility.case'),
        ),
    ]
