# Generated by Django 6.0.6 on 2026-06-16 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=150)),
                ('commission_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='compatibility.pcbuild')),
                ('referrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
