# Generated by Django 6.0.6 on 2026-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0008_pricealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='color',
            field=models.CharField(blank=True, default='Black', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='side_panel',
            field=models.CharField(blank=True, default='Tempered Glass', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='core_count',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_slots',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
    ]
